Sbhuller/flx cc
DUNE-DAQ/flxlibs pull request #101
Opened 2022-11-16 08:28 UTC by ShyamB97

- adds some error messages when certain elinks are not aligned
 - adds firmware tpg option to the card controller to configure the tp links

2022-11-16 11:09 UTC, wesketchum commented
Tested and seems ok in recent runs at least.

2022-11-16 11:56 UTC, roland-sipos requested changes
LGTM, with elimination of hardcoded link ID.

2022-11-16 11:56 UTC, roland-sipos commented on plugins/FelixCardController.cpp
> +        if(li.link_id != 5 && !lu.emu_fanout && !is_aligned){
Please make this configurable! No hardcoded link IDs from now on please. 
I would propose to introduce a "aligned_link_mask" or "ignore_alignment_links" map through configuration.

2022-11-16 11:56 UTC, roland-sipos commented on src/CardControllerWrapper.cpp
> + if(bad_channels > 2){ // Here I am assuming that the total number of links is 12 per card, so 2 are reserved for tp links and are expected to not be aligned.
See previous comment. Bad channels: expected alignment mask - ignored alignment mask

2022-11-17 08:42 UTC, roland-sipos commented
Also, just realized, that this change in its current form will break other front-end readouts (e.g.: DAPHNE) that utilizes all 6 channels from an SLR. So these changes are not firmware agnostic.

2022-11-17 10:14 UTC, ShyamB97 commented
so the changes I made were to add an ignore_alignment mask which is used when checking the alignment at init and get_info. The list is set in configuration and is done per SLR.
Need to test now.

2022-11-17 11:34 UTC, ShyamB97 commented
@roland-sipos @wesketchum tests on np04-srv-026 done, all looks good

2022-11-17 13:33 UTC, roland-sipos commented on src/CardControllerWrapper.cpp
> +    if(bad_channels > misalignment_size){
You check misalignment on init?

2022-11-17 13:33 UTC, roland-sipos commented on plugins/FelixCardController.cpp
>       if(m_card_wrappers.size() == 1) {
Misalignment will be checked only on SLR1?

2022-11-17 15:58 UTC, ShyamB97 commented
@roland-sipos  wrote separate method for link alignment check used in both init and get_info of card controller

2022-11-17 16:04 UTC, roland-sipos commented on scripts/flx.json
> +        "ignore_alignment_mask": [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]]
Shouldn't the alignment_mask be this?? Instead of the ignore one (which is empty by default)?

2022-11-17 17:14 UTC, roland-sipos approved these changes
LGTM, thanks

2022-11-17 17:14 UTC, merged